export const formats = [
  "highlight",
  "header",
  "font",
  "size",
  "bold",
  "italic",
  "underline",
  "strike",
  "color",
  "background",
  "script",
  "blockquote",
  "list",
  "bullet",
  "indent",
  "link",
  "image",
  "video",
];

export const modules = {
  toolbar: [
    [{ header: [1, 2, 3, 4, 5, 6, false] }],
    [{ font: [] }],
    ["bold", "italic", "underline", "strike", "blockquote"],
    [
      { list: "ordered" },
      { list: "bullet" },
      { indent: "-1" },
      { indent: "+1" },
    ],
    [{ color: [] }],
    [{ background: [] }],
    [{ script: "sub" }],
    [{ script: "super" }],
    [{ align: [] }],
    ["link", "image", "code-block"],
    ["clean"],
  ],
};

export const personaBots = [
  "Kimberly",
  "Avery",
  "Brooklynn",
  "Leo",
  "Christian",
  "Leah",
  "Sawyer",
  "Vivian",
  "Nolan",
  "Wyatt",
  "Kingston",
  "Oliver",
  "Chase",
  "Valentina",
  "Eliza",
  "Sara",
];
